export const getStock = async (symbols: string) => {
  console.log('---  🚀 ---> | symbols:', symbols);
  return result;
};

// THIS API ----> https://rapidapi.com/sparior/api/yahoo-finance15/
// export const getStock = async (symbols: string) => {
//   try {
//     const response = await fetch(
//       // `https://yahoo-finance15.p.rapidapi.com/api/yahoo/qu/quote/${symbol}`,
//       `https://yahoo-finance15.p.rapidapi.com/api/v1/markets/stock/quotes?ticker=${symbols}`,
//       {
//         method: 'GET',
//         headers: {
//           'X-RapidAPI-Key': `${process.env.NEXT_PUBLIC_RAPIDAPI_KEY}`,
//           'X-RapidAPI-Host': 'yahoo-finance15.p.rapidapi.com',
//         },
//       }
//     ).then((res) => res.json());
//     return response;
//   } catch (error) {
//     return { error };
//   }
// };

export const getStockUsd = async (symbol: string) => {
  try {
    const response = await fetch(
      `https://api.twelvedata.com/quote?symbol=${symbol}&apikey=${process.env.NEXT_PUBLIC_TWELVEDATA_KEY}`,
      {
        headers: {
          'Accept-Encoding': 'deflate',
          Authorization: `apikey ${process.env.NEXT_PUBLIC_TWELVEDATA_KEY}`,
        },
      }
    ).then((res) => res.json());
    return response;
  } catch (error) {
    return { error };
  }
};

const result: any = {
  meta: {
    version: 'v1.0',
    status: 200,
    copywrite: 'https://devAPI.ai',
    symbol: 'Quotes Data',
    processedTime: '2023-11-09T02:14:51.164151Z',
  },
  body: [
    {
      preMarketChange: null,
      preMarketChangePercent: null,
      preMarketPrice: null,
      preMarketTime: null,
      postMarketChange: null,
      postMarketChangePercent: null,
      postMarketPrice: null,
      postMarketTime: null,
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      typeDisp: 'Equity',
      quoteSourceName: 'Delayed Quote',
      triggerable: false,
      customPriceAlertConfidence: 'LOW',
      currency: 'BRL',
      marketState: 'POSTPOST',
      regularMarketChangePercent: 2.0346608,
      regularMarketPrice: 13.54,
      exchange: 'SAO',
      shortName: 'PAYPAL HOLD DRN',
      longName: 'PayPal Holdings, Inc.',
      messageBoardId: 'finmb_112732',
      exchangeTimezoneName: 'America/Sao_Paulo',
      exchangeTimezoneShortName: 'BRT',
      gmtOffSetMilliseconds: -10800000,
      market: 'br_market',
      esgPopulated: false,
      firstTradeDateMilliseconds: 1560776400000,
      priceHint: 2,
      regularMarketChange: 0.2699995,
      regularMarketTime: 1699476880,
      regularMarketDayHigh: 0,
      regularMarketDayRange: '0.0 - 0.0',
      regularMarketDayLow: 0,
      regularMarketVolume: 0,
      regularMarketPreviousClose: 13.27,
      bid: 13.09,
      ask: 13.75,
      fullExchangeName: 'São Paulo',
      financialCurrency: 'USD',
      regularMarketOpen: 0,
      averageDailyVolume3Month: 60456,
      averageDailyVolume10Day: 53894,
      fiftyTwoWeekLowChange: 13.54,
      fiftyTwoWeekRange: '0.0 - 24.52',
      fiftyTwoWeekHighChange: -10.9800005,
      fiftyTwoWeekHighChangePercent: -0.44779772,
      fiftyTwoWeekLow: 0,
      fiftyTwoWeekHigh: 24.52,
      fiftyTwoWeekChangePercent: -43.242085,
      trailingAnnualDividendRate: 0,
      trailingPE: 16.512196,
      trailingAnnualDividendYield: 0,
      epsTrailingTwelveMonths: 0.82,
      sharesOutstanding: 21562800128,
      bookValue: 18.278,
      fiftyDayAverage: 14.5062,
      fiftyDayAverageChange: -0.9661999,
      marketCap: 292818747392,
      fiftyDayAverageChangePercent: -0.06660599,
      twoHundredDayAverage: 16.7847,
      twoHundredDayAverageChange: -3.2447004,
      twoHundredDayAverageChangePercent: -0.19331297,
      priceToBook: 0.74078125,
      sourceInterval: 15,
      exchangeDataDelayedBy: 15,
      tradeable: false,
      cryptoTradeable: false,
      symbol: 'PYPL34.SA',
    },
    {
      preMarketChange: null,
      preMarketChangePercent: null,
      preMarketPrice: null,
      preMarketTime: null,
      postMarketChange: null,
      postMarketChangePercent: null,
      postMarketPrice: null,
      postMarketTime: null,
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      typeDisp: 'Equity',
      quoteSourceName: 'Delayed Quote',
      triggerable: false,
      customPriceAlertConfidence: 'LOW',
      currency: 'BRL',
      marketState: 'POSTPOST',
      regularMarketChangePercent: 0.599712,
      regularMarketPrice: 238.2,
      exchange: 'SAO',
      shortName: 'ISHARE SP500CI',
      longName:
        'iShares S&P 500 Fundo de Investimento - Investimento No Exterior',
      messageBoardId: 'finmb_261789599',
      exchangeTimezoneName: 'America/Sao_Paulo',
      exchangeTimezoneShortName: 'BRT',
      gmtOffSetMilliseconds: -10800000,
      market: 'br_market',
      esgPopulated: false,
      firstTradeDateMilliseconds: 1398776400000,
      priceHint: 2,
      regularMarketChange: 1.4199982,
      regularMarketTime: 1699478160,
      regularMarketDayHigh: 0,
      regularMarketDayRange: '0.0 - 0.0',
      regularMarketDayLow: 0,
      regularMarketVolume: 0,
      regularMarketPreviousClose: 236.78,
      bid: 237.83,
      ask: 237.9,
      bidSize: 0,
      askSize: 0,
      fullExchangeName: 'São Paulo',
      regularMarketOpen: 0,
      averageDailyVolume3Month: 412701,
      averageDailyVolume10Day: 419925,
      fiftyTwoWeekLowChange: 238.2,
      fiftyTwoWeekRange: '0.0 - 248.84',
      fiftyTwoWeekHighChange: -10.639999,
      fiftyTwoWeekHighChangePercent: -0.042758398,
      fiftyTwoWeekLow: 0,
      fiftyTwoWeekHigh: 248.84,
      fiftyTwoWeekChangePercent: 1.9037485,
      fiftyDayAverage: 240.3932,
      fiftyDayAverageChange: -2.1932068,
      fiftyDayAverageChangePercent: -0.009123414,
      twoHundredDayAverage: 234.6311,
      twoHundredDayAverageChange: 3.5688934,
      twoHundredDayAverageChangePercent: 0.015210657,
      sourceInterval: 15,
      exchangeDataDelayedBy: 15,
      tradeable: false,
      cryptoTradeable: false,
      symbol: 'IVVB11.SA',
    },
    {
      preMarketChange: null,
      preMarketChangePercent: null,
      preMarketPrice: null,
      preMarketTime: null,
      postMarketChange: null,
      postMarketChangePercent: null,
      postMarketPrice: null,
      postMarketTime: null,
      language: 'en-US',
      region: 'US',
      quoteType: 'ETF',
      typeDisp: 'ETF',
      quoteSourceName: 'Delayed Quote',
      triggerable: true,
      customPriceAlertConfidence: 'HIGH',
      currency: 'CAD',
      marketState: 'POSTPOST',
      regularMarketChangePercent: 0.3645876,
      regularMarketPrice: 107.36,
      exchange: 'TOR',
      shortName: 'VANGUARD SP 500 INDEX ETF',
      longName: 'Vanguard S&P 500 Index ETF',
      messageBoardId: 'finmb_216607795',
      exchangeTimezoneName: 'America/Toronto',
      exchangeTimezoneShortName: 'EST',
      gmtOffSetMilliseconds: -18000000,
      market: 'ca_market',
      esgPopulated: false,
      firstTradeDateMilliseconds: 1352385000000,
      priceHint: 2,
      regularMarketChange: 0.3899994,
      regularMarketTime: 1699477196,
      regularMarketDayHigh: 107.42,
      regularMarketDayRange: '106.84 - 107.42',
      regularMarketDayLow: 106.84,
      regularMarketVolume: 134404,
      regularMarketPreviousClose: 106.97,
      bid: 107.33,
      ask: 107.35,
      bidSize: 0,
      askSize: 0,
      fullExchangeName: 'Toronto',
      regularMarketOpen: 107.36,
      averageDailyVolume3Month: 151816,
      averageDailyVolume10Day: 172770,
      fiftyTwoWeekLowChange: 16.11,
      fiftyTwoWeekLowChangePercent: 0.17654794,
      fiftyTwoWeekRange: '91.25 - 109.38',
      fiftyTwoWeekHighChange: -2.0199966,
      fiftyTwoWeekHighChangePercent: -0.018467696,
      fiftyTwoWeekLow: 91.25,
      fiftyTwoWeekHigh: 109.38,
      fiftyTwoWeekChangePercent: 14.210976,
      trailingPE: 22.715614,
      dividendYield: 1.29,
      ytdReturn: 11.0086,
      trailingThreeMonthReturns: -4.6506,
      trailingThreeMonthNavReturns: -4.6506,
      netAssets: 8889361400,
      epsTrailingTwelveMonths: 4.7262645,
      fiftyDayAverage: 105.2768,
      fiftyDayAverageChange: 2.0831985,
      fiftyDayAverageChangePercent: 0.019787822,
      twoHundredDayAverage: 101.7653,
      twoHundredDayAverageChange: 5.5947037,
      twoHundredDayAverageChangePercent: 0.054976538,
      sourceInterval: 15,
      exchangeDataDelayedBy: 15,
      tradeable: false,
      cryptoTradeable: false,
      symbol: 'VFV.TO',
    },
    {
      preMarketChange: null,
      preMarketChangePercent: null,
      preMarketPrice: null,
      preMarketTime: null,
      postMarketChange: null,
      postMarketChangePercent: null,
      postMarketPrice: null,
      postMarketTime: null,
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      typeDisp: 'Equity',
      quoteSourceName: 'Delayed Quote',
      triggerable: false,
      customPriceAlertConfidence: 'LOW',
      currency: 'BRL',
      marketState: 'POSTPOST',
      regularMarketChangePercent: 0.071340494,
      regularMarketPrice: 70.13,
      exchange: 'SAO',
      shortName: 'VALE        ON      NM',
      longName: 'Vale S.A.',
      messageBoardId: 'finmb_874225',
      exchangeTimezoneName: 'America/Sao_Paulo',
      exchangeTimezoneShortName: 'BRT',
      gmtOffSetMilliseconds: -10800000,
      market: 'br_market',
      esgPopulated: false,
      firstTradeDateMilliseconds: 946900800000,
      priceHint: 2,
      regularMarketChange: 0.049995422,
      regularMarketTime: 1699477659,
      regularMarketDayHigh: 0,
      regularMarketDayRange: '0.0 - 0.0',
      regularMarketDayLow: 0,
      regularMarketVolume: 0,
      regularMarketPreviousClose: 70.08,
      bid: 70.11,
      ask: 70.14,
      bidSize: 0,
      askSize: 0,
      fullExchangeName: 'São Paulo',
      financialCurrency: 'USD',
      regularMarketOpen: 0,
      averageDailyVolume3Month: 25784737,
      averageDailyVolume10Day: 29877277,
      fiftyTwoWeekLowChange: 70.13,
      fiftyTwoWeekRange: '0.0 - 98.29',
      fiftyTwoWeekHighChange: -28.160004,
      fiftyTwoWeekHighChangePercent: -0.28649917,
      fiftyTwoWeekLow: 0,
      fiftyTwoWeekHigh: 98.29,
      fiftyTwoWeekChangePercent: -5.995977,
      earningsTimestamp: 1698415200,
      earningsTimestampStart: 1698415200,
      earningsTimestampEnd: 1698415200,
      trailingAnnualDividendRate: 1.524,
      trailingPE: 6.9504457,
      dividendRate: 6.37,
      trailingAnnualDividendYield: 0.021746576,
      dividendYield: 8.91,
      epsTrailingTwelveMonths: 10.09,
      epsForward: 11.9,
      epsCurrentYear: 10.48,
      priceEpsCurrentYear: 6.691794,
      sharesOutstanding: 4302850048,
      bookValue: 8.829,
      fiftyDayAverage: 67.304,
      fiftyDayAverageChange: 2.8259964,
      marketCap: 308605681664,
      fiftyDayAverageChangePercent: 0.041988537,
      twoHundredDayAverage: 71.9106,
      twoHundredDayAverageChange: -1.7806015,
      twoHundredDayAverageChangePercent: -0.024761323,
      forwardPE: 5.893277,
      priceToBook: 7.943141,
      sourceInterval: 15,
      exchangeDataDelayedBy: 15,
      averageAnalystRating: '2.3 - Buy',
      tradeable: false,
      cryptoTradeable: false,
      symbol: 'VALE3.SA',
    },
    {
      preMarketChange: null,
      preMarketChangePercent: null,
      preMarketPrice: null,
      preMarketTime: null,
      postMarketChange: null,
      postMarketChangePercent: null,
      postMarketPrice: null,
      postMarketTime: null,
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      typeDisp: 'Equity',
      quoteSourceName: 'Delayed Quote',
      triggerable: true,
      customPriceAlertConfidence: 'HIGH',
      currency: 'CAD',
      marketState: 'POSTPOST',
      regularMarketChangePercent: 0.1312366,
      regularMarketPrice: 7.63,
      exchange: 'TOR',
      shortName: 'GALAXY DIGITAL HOLDINGS LTD',
      longName: 'Galaxy Digital Holdings Ltd.',
      messageBoardId: 'finmb_24208067',
      exchangeTimezoneName: 'America/Toronto',
      exchangeTimezoneShortName: 'EST',
      gmtOffSetMilliseconds: -18000000,
      market: 'ca_market',
      esgPopulated: false,
      firstTradeDateMilliseconds: 1595511000000,
      priceHint: 2,
      regularMarketChange: 0.010000229,
      regularMarketTime: 1699477200,
      regularMarketDayHigh: 7.64,
      regularMarketDayRange: '7.32 - 7.64',
      regularMarketDayLow: 7.32,
      regularMarketVolume: 614600,
      regularMarketPreviousClose: 7.62,
      bid: 7.59,
      ask: 7.63,
      fullExchangeName: 'Toronto',
      financialCurrency: 'USD',
      regularMarketOpen: 7.59,
      averageDailyVolume3Month: 439198,
      averageDailyVolume10Day: 947060,
      fiftyTwoWeekLowChange: 4.3050003,
      fiftyTwoWeekLowChangePercent: 1.2947369,
      fiftyTwoWeekRange: '3.325 - 7.655',
      fiftyTwoWeekHighChange: -0.025000095,
      fiftyTwoWeekHighChangePercent: -0.0032658516,
      fiftyTwoWeekLow: 3.325,
      fiftyTwoWeekHigh: 7.655,
      fiftyTwoWeekChangePercent: 62.82052,
      dividendDate: 1533081600,
      earningsTimestamp: 1699536600,
      earningsTimestampStart: 1699536600,
      earningsTimestampEnd: 1699536600,
      trailingAnnualDividendRate: 0,
      trailingAnnualDividendYield: 0,
      dividendYield: 12.3,
      epsTrailingTwelveMonths: -3.83,
      epsForward: -0.67,
      epsCurrentYear: 0,
      sharesOutstanding: 107000000,
      bookValue: 4.324,
      fiftyDayAverage: 5.3006,
      fiftyDayAverageChange: 2.3294,
      marketCap: 2353893120,
      fiftyDayAverageChangePercent: 0.43945968,
      twoHundredDayAverage: 5.266,
      twoHundredDayAverageChange: 2.3640003,
      twoHundredDayAverageChangePercent: 0.44891766,
      forwardPE: -11.38806,
      priceToBook: 1.7645699,
      sourceInterval: 15,
      exchangeDataDelayedBy: 15,
      averageAnalystRating: '1.7 - Buy',
      tradeable: false,
      cryptoTradeable: false,
      symbol: 'GLXY.TO',
    },
  ],
};
