import './globals.css';
import type { Metadata } from 'next';
import { Gabarito, Cairo_Play, Inter } from 'next/font/google';
import { getServerSession } from 'next-auth';
import SessionProvider from '../components/SessionProvider';
import Header from '../components/Header';

// export const gabarito = Gabarito({ subsets: ['latin'], display: 'swap' });
// export const cairoPlay = Cairo_Play({ subsets: ['latin'], display: 'swap' });
export const inter = Inter({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className='mx-auto max-w-[1400px] text-xl gap-2 border-2 border-yellow-300'>
            <Header />

            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
