export const hardcodedAthCoins = [
  { symbol: 'BTC', ath: 69045 },
  { symbol: 'AGIX', ath: 0.63 },
  { symbol: 'HBAR', ath: 0.57 },
  { symbol: 'SOL', ath: 260.06 },
  { symbol: 'APE', ath: 39.4 },
  { symbol: 'ROSE', ath: 0.59 },
  { symbol: 'ENJ', ath: 4.85 },
  { symbol: 'OCEAN', ath: 1.94 },
  { symbol: 'SAND', ath: 8.44 },
  { symbol: 'ETH', ath: 4878.26 },
  { symbol: 'USDT', ath: 1.32 },
  { symbol: 'BNB', ath: 686.31 },
  { symbol: 'XRP', ath: 3.4 },
  { symbol: 'USDC', ath: 1.17 },
  { symbol: 'SOL', ath: 259.96 },
  { symbol: 'STETH', ath: 4829.57 },
  { symbol: 'ADA', ath: 3.09 },
  { symbol: 'DOGE', ath: 0.731578 },
  { symbol: 'TRX', ath: 0.231673 },
  { symbol: 'LINK', ath: 52.7 },
  { symbol: 'MATIC', ath: 2.92 },
  { symbol: 'AVAX', ath: 144.96 },
  { symbol: 'DOT', ath: 54.98 },
  { symbol: 'WBTC', ath: 70643 },
  { symbol: 'DAI', ath: 1.22 },
  { symbol: 'LTC', ath: 410.26 },
  { symbol: 'TON', ath: 5.29 },
  { symbol: 'SHIB', ath: 0.00008616 },
  { symbol: 'BCH', ath: 3785.82 },
  { symbol: 'UNI', ath: 44.92 },
  { symbol: 'LEO', ath: 8.14 },
  { symbol: 'OKB', ath: 64.92 },
  { symbol: 'XLM', ath: 0.875563 },
  { symbol: 'TUSD', ath: 1.62 },
  { symbol: 'XMR', ath: 542.33 },
  { symbol: 'KAS', ath: 0.152699 },
  { symbol: 'ETC', ath: 167.09 },
  { symbol: 'ATOM', ath: 44.45 },
  { symbol: 'CRO', ath: 0.965407 },
  { symbol: 'FIL', ath: 236.84 },
  { symbol: 'HBAR', ath: 0.569229 },
  { symbol: 'LDO', ath: 7.3 },
  { symbol: 'ICP', ath: 700.65 },
  { symbol: 'APT', ath: 19.92 },
  { symbol: 'NEAR', ath: 20.44 },
  { symbol: 'BUSD', ath: 1.15 },
  { symbol: 'IMX', ath: 9.52 },
  { symbol: 'RUNE', ath: 20.87 },
  { symbol: 'VET', ath: 0.280991 },
  { symbol: 'OP', ath: 3.22 },
  { symbol: 'MNT', ath: 0.600075 },
  { symbol: 'TAO', ath: 306.96 },
  { symbol: 'QNT', ath: 427.42 },
  { symbol: 'AAVE', ath: 661.69 },
  { symbol: 'ARB', ath: 8.67 },
  { symbol: 'INJ', ath: 24.89 },
  { symbol: 'GRT', ath: 2.84 },
  { symbol: 'MKR', ath: 6292.31 },
  { symbol: 'RNDR', ath: 8.78 },
  { symbol: 'RETH', ath: 4814.31 },
  { symbol: 'EGLD', ath: 545.64 },
  { symbol: 'ALGO', ath: 3.56 },
  { symbol: 'SNX', ath: 28.53 },
  { symbol: 'FLOW', ath: 42.4 },
  { symbol: 'THETA', ath: 15.72 },
  { symbol: 'BSV', ath: 489.75 },
  { symbol: 'STX', ath: 3.39 },
  { symbol: 'FTM', ath: 3.46 },
  { symbol: 'SAND', ath: 8.4 },
  { symbol: 'TIA', ath: 7.33 },
  { symbol: 'AXS', ath: 164.9 },
  { symbol: 'EOS', ath: 22.71 },
  { symbol: 'NEO', ath: 198.38 },
  { symbol: 'WBT', ath: 14.64 },
  { symbol: 'MANA', ath: 5.85 },
  { symbol: 'BGB', ath: 0.583922 },
  { symbol: 'XTZ', ath: 9.12 },
  { symbol: 'GALA', ath: 0.824837 },
  { symbol: 'KAVA', ath: 9.12 },
  { symbol: 'KCS', ath: 28.83 },
  { symbol: 'USDD', ath: 1.052 },
  { symbol: 'XDC', ath: 0.192754 },
  { symbol: 'FDUSD', ath: 1.041 },
  { symbol: 'FRAX', ath: 1.14 },
  { symbol: 'ILV', ath: 1911.26 },
  { symbol: 'MINA', ath: 9.09 },
  { symbol: 'CAKE', ath: 43.96 },
  { symbol: 'FRXETH', ath: 2134.61 },
  { symbol: 'GT', ath: 12.94 },
  { symbol: 'KLAY', ath: 4.34 },
  { symbol: 'TKX', ath: 22.3 },
  { symbol: 'WEMIX', ath: 24.71 },
  { symbol: 'XEC', ath: 0.00038001 },
  { symbol: 'XRD', ath: 0.651264 },
  { symbol: 'CHEEL', ath: 17.32 },
  { symbol: 'IOTA', ath: 5.25 },
  { symbol: 'APE', ath: 26.7 },
  { symbol: 'ETHDYDX', ath: 27.86 },
  { symbol: 'RPL', ath: 61.9 },
  { symbol: 'FET', ath: 1.17 },
  { symbol: 'CFX', ath: 1.7 },
  { symbol: 'SUI', ath: 2.16 },
  { symbol: 'FXS', ath: 42.8 },
  { symbol: 'AR', ath: 89.24 },
  { symbol: 'RLB', ath: 0.264358 },
  { symbol: 'CHZ', ath: 0.878633 },
  { symbol: 'CRV', ath: 15.37 },
  { symbol: 'TWT', ath: 2.72 },
];

export const annualInflationData = {
  2022: 0.08, // 8.0%
  2023: 0.041, // 4.1%
  2024: 0.034, // 3.4%
  2025: 0.025, // 2.5% (est.)
};

// Calculate cumulative multiplier from 2022 to present
const inflationMultiplier = Object.values(annualInflationData).reduce(
  (acc, rate) => acc * (1 + rate),
  1
);

export { inflationMultiplier };

export const retirementData = [
  { flag: '🇵🇰', country: 'Pakistan', cost: 158410, continent: 'Asia' },
  { flag: '🇮🇳', country: 'India', cost: 186353, continent: 'Asia' },
  { flag: '🇨🇴', country: 'Colombia', cost: 199833, continent: 'South America' },
  { flag: '🇩🇿', country: 'Algeria', cost: 210991, continent: 'Africa' },
  { flag: '🇹🇳', country: 'Tunisia', cost: 215610, continent: 'Africa' },
  { flag: '🇪🇬', country: 'Egypt', cost: 217388, continent: 'Africa' },
  { flag: '🇱🇰', country: 'Sri Lanka', cost: 224815, continent: 'Asia' },
  { flag: '🇳🇵', country: 'Nepal', cost: 225091, continent: 'Asia' },
  {
    flag: '🇲🇰',
    country: 'Macedonia (North)',
    cost: 228719,
    continent: 'Europe',
  },
  { flag: '🇽🇰', country: 'Kosovo', cost: 230199, continent: 'Europe' },
  { flag: '🇧🇩', country: 'Bangladesh', cost: 231296, continent: 'Asia' },
  { flag: '🇰🇿', country: 'Kazakhstan', cost: 232663, continent: 'Asia' },
  { flag: '🇬🇭', country: 'Ghana', cost: 233166, continent: 'Africa' },
  { flag: '🇦🇿', country: 'Azerbaijan', cost: 236531, continent: 'Asia' },
  { flag: '🇺🇬', country: 'Uganda', cost: 240366, continent: 'Africa' },
  { flag: '🇰🇪', country: 'Kenya', cost: 240593, continent: 'Africa' },
  { flag: '🇺🇿', country: 'Uzbekistan', cost: 243549, continent: 'Asia' },
  { flag: '🇺🇦', country: 'Ukraine', cost: 244896, continent: 'Europe' },
  {
    flag: '🇧🇦',
    country: 'Bosnia and Herzegovina',
    cost: 247333,
    continent: 'Europe',
  },
  { flag: '🇲🇦', country: 'Morocco', cost: 249450, continent: 'Africa' },
  {
    flag: '🇦🇷',
    country: 'Argentina',
    cost: 254747,
    continent: 'South America',
  },
  { flag: '🇲🇩', country: 'Moldova', cost: 255851, continent: 'Europe' },
  { flag: '🇮🇶', country: 'Iraq', cost: 255857, continent: 'Asia' },
  { flag: '🇹🇿', country: 'Tanzania', cost: 261525, continent: 'Africa' },
  { flag: '🇮🇩', country: 'Indonesia', cost: 262988, continent: 'Asia' },
  { flag: '🇵🇪', country: 'Peru', cost: 267330, continent: 'South America' },
  { flag: '🇧🇷', country: 'Brazil', cost: 271304, continent: 'South America' },
  { flag: '🇦🇱', country: 'Albania', cost: 275366, continent: 'Europe' },
  { flag: '🇹🇷', country: 'Turkey', cost: 279439, continent: 'Europe/Asia' },
  { flag: '🇵🇭', country: 'Philippines', cost: 279495, continent: 'Asia' },
  { flag: '🇧🇾', country: 'Belarus', cost: 281631, continent: 'Europe' },
  { flag: '🇨🇱', country: 'Chile', cost: 283000, continent: 'South America' },
  { flag: '🇷🇸', country: 'Serbia', cost: 284836, continent: 'Europe' },
  {
    flag: '🇻🇪',
    country: 'Venezuela',
    cost: 284166,
    continent: 'South America',
  },
  { flag: '🇲🇾', country: 'Malaysia', cost: 288233, continent: 'Asia' },
  { flag: '🇭🇺', country: 'Hungary', cost: 288961, continent: 'Europe' },
  { flag: '🇷🇴', country: 'Romania', cost: 289851, continent: 'Europe' },
  { flag: '🇪🇨', country: 'Ecuador', cost: 292330, continent: 'South America' },
  { flag: '🇧🇬', country: 'Bulgaria', cost: 297079, continent: 'Europe' },
  { flag: '🇲🇪', country: 'Montenegro', cost: 298029, continent: 'Europe' },
  { flag: '🇲🇽', country: 'Mexico', cost: 307460, continent: 'North America' },
  { flag: '🇿🇦', country: 'South Africa', cost: 309153, continent: 'Africa' },
  { flag: '🇹🇭', country: 'Thailand', cost: 317163, continent: 'Asia' },
  { flag: '🇲🇺', country: 'Mauritius', cost: 320338, continent: 'Africa' },
  { flag: '🇵🇱', country: 'Poland', cost: 322785, continent: 'Europe' },
  { flag: '🇻🇳', country: 'Vietnam', cost: 339141, continent: 'Asia' },
  { flag: '🇭🇷', country: 'Croatia', cost: 344915, continent: 'Europe' },
  { flag: '🇸🇰', country: 'Slovakia', cost: 348517, continent: 'Europe' },
  { flag: '🇱🇻', country: 'Latvia', cost: 354474, continent: 'Europe' },
  { flag: '🇬🇪', country: 'Georgia', cost: 355189, continent: 'Asia' },
  {
    flag: '🇩🇴',
    country: 'Dominican Republic',
    cost: 356559,
    continent: 'North America',
  },
  { flag: '🇸🇦', country: 'Saudi Arabia', cost: 357363, continent: 'Asia' },
  { flag: '🇨🇳', country: 'China', cost: 364786, continent: 'Asia' },
  { flag: '🇬🇷', country: 'Greece', cost: 365521, continent: 'Europe' },
  { flag: '🇸🇮', country: 'Slovenia', cost: 370701, continent: 'Europe' },
  { flag: '🇳🇬', country: 'Nigeria', cost: 376269, continent: 'Africa' },
  {
    flag: '🇨🇷',
    country: 'Costa Rica',
    cost: 378721,
    continent: 'North America',
  },
  { flag: '🇹🇼', country: 'Taiwan', cost: 380121, continent: 'Asia' },
  { flag: '🇱🇹', country: 'Lithuania', cost: 383426, continent: 'Europe' },
  {
    flag: '🇹🇹',
    country: 'Trinidad and Tobago',
    cost: 392115,
    continent: 'North America',
  },
  { flag: '🇪🇪', country: 'Estonia', cost: 403250, continent: 'Europe' },
  { flag: '🇨🇿', country: 'Czech Republic', cost: 404634, continent: 'Europe' },
  { flag: '🇮🇷', country: 'Iran', cost: 407969, continent: 'Asia' },
  { flag: '🇵🇹', country: 'Portugal', cost: 414347, continent: 'Europe' },
  { flag: '🇰🇷', country: 'South Korea', cost: 417902, continent: 'Asia' },
  { flag: '🇯🇵', country: 'Japan', cost: 418858, continent: 'Asia' },
  { flag: '🇪🇸', country: 'Spain', cost: 420065, continent: 'Europe' },
  { flag: '🇰🇼', country: 'Kuwait', cost: 421379, continent: 'Asia' },
  { flag: '🇨🇾', country: 'Cyprus', cost: 439578, continent: 'Asia' },
  { flag: '🇮🇹', country: 'Italy', cost: 451376, continent: 'Europe' },
  { flag: '🇺🇾', country: 'Uruguay', cost: 458140, continent: 'South America' },
  { flag: '🇲🇹', country: 'Malta', cost: 462234, continent: 'Europe' },
  { flag: '🇫🇮', country: 'Finland', cost: 475676, continent: 'Europe' },
  { flag: '🇦🇹', country: 'Austria', cost: 484324, continent: 'Europe' },
  { flag: '🇫🇷', country: 'France', cost: 487951, continent: 'Europe' },
  { flag: '🇧🇪', country: 'Belgium', cost: 491606, continent: 'Europe' },
  { flag: '🇸🇪', country: 'Sweden', cost: 505035, continent: 'Europe' },
  { flag: '🇳🇿', country: 'New Zealand', cost: 508531, continent: 'Oceania' },
  { flag: '🇩🇪', country: 'Germany', cost: 509100, continent: 'Europe' },
  { flag: '🇬🇧', country: 'United Kingdom', cost: 523735, continent: 'Europe' },
  { flag: '🇦🇺', country: 'Australia', cost: 544746, continent: 'Oceania' },
  { flag: '🇨🇦', country: 'Canada', cost: 557164, continent: 'North America' },
  { flag: '🇳🇱', country: 'Netherlands', cost: 594206, continent: 'Europe' },
  { flag: '🇩🇰', country: 'Denmark', cost: 603668, continent: 'Europe' },
  { flag: '🇳🇴', country: 'Norway', cost: 630068, continent: 'Europe' },
  {
    flag: '🇦🇪',
    country: 'United Arab Emirates',
    cost: 636493,
    continent: 'Asia',
  },
  { flag: '🇶🇦', country: 'Qatar', cost: 649308, continent: 'Asia' },
  { flag: '🇮🇪', country: 'Ireland', cost: 652302, continent: 'Europe' },
  { flag: '🇮🇱', country: 'Israel', cost: 656247, continent: 'Asia' },
  { flag: '🇱🇺', country: 'Luxembourg', cost: 696422, continent: 'Europe' },
  { flag: '🇮🇸', country: 'Iceland', cost: 702891, continent: 'Europe' },
  {
    flag: '🇺🇸',
    country: 'United States',
    cost: 702330,
    continent: 'North America',
  },
  { flag: '🇨🇭', country: 'Switzerland', cost: 830547, continent: 'Europe' },
  { flag: '🇸🇬', country: 'Singapore', cost: 1118375, continent: 'Asia' },
];
